/*
  Swiper reducer actions
 */
export const SWIPER_LEFT_CHANGED = 'SWIPER_LEFT_CHANGED';
export const SWIPER_LEFT_SUBSCRIBED = 'SWIPER_LEFT_SUBSCRIBED';
export const SWIPER_LEFT_UNSUBSCRIBED = 'SWIPER_LEFT_UNSUBSCRIBED';
export const SWIPER_RIGHT_CHANGED = 'SWIPER_RIGHT_CHANGED';
export const SWIPER_RIGHT_SUBSCRIBED = 'SWIPER_RIGHT_SUBSCRIBED';
export const SWIPER_RIGHT_UNSUBSCRIBED = 'SWIPER_RIGHT_UNSUBSCRIBED';
export const SWIPER_TOP_CHANGED = 'SWIPER_TOP_CHANGED';
export const SWIPER_TOP_SUBSCRIBED = 'SWIPER_TOP_SUBSCRIBED';
export const SWIPER_TOP_UNSUBSCRIBED = 'SWIPER_TOP_UNSUBSCRIBED';
export const SWIPER_PLACE_CHANGED = 'SWIPER_PLACE_CHANGED';
export const SWIPER_PHOTOS_CHANGED = 'SWIPER_PHOTOS_CHANGED';
